%web_drop_table(WORK.IMPORT);
FILENAME REFFILE '/home/u64360188/sasuser.v94/Chapter 3.4.xlsx';
PROC IMPORT DATAFILE=REFFILE
DBMS=XLSX
OUT=WORK.IMPORT;
GETNAMES=YES;
RUN;
PROC CONTENTS DATA=WORK.IMPORT; RUN;
%web_open_table(WORK.IMPORT);
data cleanup;
set import;
date_dt=substr(date,1,2);
date_m=substr(date,4,2);
date_y=substr(date,7,4);
format date_1 date9.;
date_1=mdy(date_m, date_dt, date_y);
dflt_dt=substr(default_date,1,2);
dflt_m=substr(default_date,4,2);
dflt_y=substr(default_date,7,4);
format dflt_dt_1 date9.;
dflt_dt_1=mdy(dflt_m,dflt_dt,dflt_y);
cure_dt=substr(cure_date,1,2);
cure_m=substr(cure_date,4,2);
cure_y=substr(cure_date,7,4);
format cure_dt_1 date9.;
cure_dt_1=mdy(cure_m,cure_dt,cure_y);
re_dflt_dt=substr(re_default_date,1,2);
re_dflt_m=substr(re_default_date,4,2);
re_dflt_y=substr(re_default_date,7,4);
format re_dflt_dt_1 date9.;
re_dflt_dt_1=mdy(re_dflt_m,re_dflt_dt,re_dflt_y);
if default_date ne "." then do;
dflt=1;
end;
else do;
dflt=0;
end;
run;
data cleaned (drop=dflt_dt_1 cure_dt_1 re_dflt_dt_1 date_1);
set cleanup (drop=default_date cure_date re_default_date dflt_dt dflt_m dflt_y cure_dt cure_m cure_y re_dflt_dt re_dflt_m re_dflt_y
date date_dt date_m date_y);
format default_date date9.;
default_date=dflt_dt_1;
format cure_date date9.;
cure_date=cure_dt_1;
format re_default_dt date9.;
re_default_dt=re_dflt_dt_1;
format date date9.;
date=date_1;
run;
proc sort data=cleaned;
by customer date;
run;
data model_latest_record temp;
set cleaned;
by customer date;
if last.customer and last.date then output model_latest_record;
else output temp;
run;
proc genmod data=model_latest_record descending;
Class collateral_type customer_type;
Model dflt = utilisation ltv collateral_type borrowing_portfolio_ratio postcode_index customer_type arrears/ dist=binomial;
Output out=preds p=pred l=lower u=upper;
Run;
Proc sql;
select count(customer) from cleaned where default_date ne .; quit;
/*for example*/
proc logistic data=preds descending;
model dflt = / nofit;
roc "Genmod model" pred=pred;
run;